
name: Build
on:
  push:
  workflow_dispatch:
  schedule:
    # Once week 02:18 on Saturday
    - cron: '18 2 * * Sat'

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
    group: pe-terminal-'${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
    cancel-in-progress: true

jobs:
    build:
      runs-on: ["self-hosted", "client"]
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      steps:
        - name: Check out code
          uses: actions/checkout@v4
        - name: Set up golang
          uses: actions/setup-go@v5
          with:
            go-version: '1.20'
        - name: Golang version
          run: go version
        - name: go build
          run: go build ./...
        - name: Run make.sh test (go vet + go test)
          run:  ./make.sh test
        - name: Post status to Slack testing_builds
          if: always()
          uses: act10ns/slack@v2
          with:
            status: ${{ job.status }}
            channel: '#testing_builds'     