name: Build
on: 
  push:
      # Don't run if only the .md -file is changed
      paths-ignore:
        - '**/*.md'

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: pe-terminal-'${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  go-build-and-checks:
    strategy:
      matrix:
        # Can't use 1.15 because io.Discard is not defined
        golang-ver: ["1.16", "1.17", "1.18", "1.19", "1.20"]
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up golang
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.golang-ver }}
      - name: Golang version
        run: go version
      - name: Set GitHub access token via git config
        run: | 
          git config --global url."https://${{ secrets.ACCESS_TOKEN }}@github.com/".insteadOf "git@github.com:"
          git config --global url."https://${{ secrets.ACCESS_TOKEN }}@github".insteadOf "https://github"
      - run: sudo apt install golint
      - run: git clone git@github.com:PelionIoT/scripts-internal.git
      - name: Build all
        run: scripts-internal/golang/go_build_script.sh --all
      - name: Run make.sh test (go vet + go test)
        run:  ./make.sh test

  pysh-check:
    runs-on: ubuntu-latest
    steps:
      - name: Set GitHub access token via git config
        run: | 
          git config --global url."https://${{ secrets.ACCESS_TOKEN }}@github.com/".insteadOf "git@github.com:"
          git config --global url."https://${{ secrets.ACCESS_TOKEN }}@github".insteadOf "https://github"
      - name: Check out code
        uses: actions/checkout@v3
      - run: git clone git@github.com:PelionIoT/scripts-internal.git
      - name: Run pysh-check
        run: |
           sudo apt install pycodestyle pydocstyle black
           echo "." >scripts-internal/.nopyshcheck
           echo "." >vendor/.nopyshcheck
           scripts-internal/pysh-check/pysh-check.sh --workdir .